### ISSUE TITLE
Cannot read property 'filename' of undefined

### ISSUE THREAD

**Issue by DesdeJorge** [keyurbhole/htmltopdf#19]
After deploy of layers and functions, testing it show the next error: 

`{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'filename' of undefined",
    "trace": [
        "TypeError: Cannot read property 'filename' of undefined",
        "    at execPdfToBuffer (/var/task/node_modules/html-pdf/lib/pdf.js:48:21)",
        "    at ChildProcess.respond (/var/task/node_modules/html-pdf/lib/pdf.js:144:5)",
        "    at ChildProcess.emit (events.js:314:20)",
        "    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)"
    ]
}`

**Comment by dgastudio** [comment]
same here

**Comment by dgastudio** [comment]
fixed by adding localUrlAccess: true to pdf.create
also, needed to extend timeout to 20 sec

**Comment by DesdeJorge** [comment]
Fixed by changing the binary of phantomjs:

1. Go to https://phantomjs.org/download.html and download the linux 64-bit version
2. Unzip and go to bin folder and replace the file **phantomjs_linux-x86_64** in layers/executables folder.
3. `
   cd layers/executables
   sls deploy
`
4. Test again and enjoy!

**Comment by atrudeau-vitall** [comment]
@DesdeJorge I was struggling with this exact issue for a week, thanks for the solution it worked for me
